name: Deploy App to Azure App Servvice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Soruce
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: springboot-azure-example
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from build jobs
        uses: actions/download-artifact@v2
        with:
          name: springboot-azure-example
      - name: Deploy to Azure App Service
        uses: actions/webapps-deploy@v2
        with:
          app-name: EmpDetailsWebApp
          publish-profile: ${{ secrets.azureWebAppPublishProfile}}
          package: '*.jar'