name: Deploy App to Azure App Servvice

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: mvn clean install -DskipTests
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: EmpDetailsWebApp
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: target/*.jar